image: node:latest

stages:
  - test
  - build

cache:
  paths:
  - node_modules/
  
before_script:
  - npm install

test:
  stage: test
  script: npm run test

build:
  stage: build
  script: npm run build
  artifacts:
    paths: 
    - dist
    untracked: true

